# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

app_title: "NSFREU Demo (Your App Title)"
university: "Your University"
department: "Your Department"
department_url: "http://reu.ucsd.edu"
department_mailing_address: "1234 Your Address, Your City, Your Zip"
application_start: Mon, 15 Aug 2012 00:00:00 -0700
application_deadline: Tue, 6 Mar 2013 00:00:00 -0700
notification_date: Mon, 2 Apr 2013 00:00:00 -0700
program_start_date: Mon, 11 Jun 2012
program_end_date: Mon, 20 Aug 2013
check_back_date: Fri, 1 Feb 2014
mail_from: reu@ucsd.edu
password_min_length: 6
attachment_max_size: 10240
general_description: "General Description\n\nThe National Science Foundation's Research Experience for Undergraduates (NSF-REU) program provides undergraduate students access to state-of-the-art facilities, the opportunity to work with accomplished and experienced faculty mentors, and to participate in highly collaborative, cutting-edge research projects"
highlights: "Highlights\n\n* $X,XXX stipend\n* On-campus housing or housing allowance\n* Travel to and from the REU Site\n* Hands-on research experience\n* Weekly professional development workshops\n* Social events"
eligibility_requirements: "Eligibility Requirements\n\n* Full-time undergraduate student\n* U.S. citizen or permanent resident"
application_information: "Application Information\n\n* Major components of the online application include: a personal statement, a copy of your unofficial school transcript (as a pdf), and contact information for one reference\n* The person writing your letter of recommendation will be contacted via e-mail and will submit their letter online\n* Once you begin an application, you can check the status of it any time by logging into this website\n* Only complete applications will be reviewed"
development:
  mailer_host: "localhost:3000"
test:
  mailer_host: "test.local"
production:
  mailer_host: "reu.ucsd.edu"

