--- 
user: mongrel
group: www-data
cwd: /var/www/rails/nsfreu/current/
log_file: /var/log/mongrel/nsfreu.log
port: "8010"
environment: production
address: 127.0.0.1
pid_file: /var/run/mongrel_cluster/nsfreu.pid
servers: 2