app_title:
  default: NSFREU Demo (Your App Title Here)
domain:
  default: www.be.ucsd.edu/nsfreudemo
university:
  default: UC San Diego
department:
  default: Department of Bioengineering
application_start:
  default: Mon, 15 Aug 2011 00:00:00 -0700
application_deadline:
  default: Tue, 6 Mar 2012 00:00:00 -0700
notification_date:
  default: Mon, 2 Apr 2012 00:00:00 -0700
program_start_date:
  default: Mon, 11 Jun 2012
program_end_date:
  default: Mon, 20 Aug 2012
check_back_date:
  default: Fri, 1 Feb 2013
mail_from:
  default: nsfreu@be.ucsd.edu
password_min_length:
  format: int
  default: 6
attachment_max_size:
  format: int
  default: 10240
general_description:
  default: "h3. General Description\n\nThe National Science Foundation's Research Experience for Undergraduates (NSF-REU) program provides undergraduate students access to state-of-the-art facilities, the opportunity to work with accomplished and experienced faculty mentors, and to participate in highly collaborative, cutting-edge research projects.\n"
highlights:
  default: "h4. Highlights\n\n* $X,XXX stipend\n* On-campus housing or housing allowance\n* Travel to and from the REU Site\n* Hands-on research experience\n* Weekly professional development workshops\n* Social events"
eligibility_requirements:
  default: "h4. Eligibility Requirements\n\n* Full-time undergraduate student\n* U.S. citizen or permanent resident"
application_information:
  default: "h4. Application Information\n\n* Major components of the online application include: a personal statement, a copy of your unofficial school transcript (as a pdf), and contact information for one reference\n* The person writing your letter of recommendation will be contacted via e-mail and will submit their letter online\n* Once you begin an application, you can check the status of it any time by logging into this website\n* Only complete applications will be reviewed"
  