app_title:
  default: REU in Regenerative Medicine, Multi-Scale Bioengineering, and Systems Biology
domain:
  default: reumanager.com/be
university:
  default: UC San Diego
department:
  default: Department of Bioengineering
application_start:
  default: Wed, 9 Jan 2013 00:00:00 -0700
application_deadline:
  default: Wed, 6 Mar 2013 00:00:00 -0700
notification_date:
  default: Tue, 2 Apr 2013 00:00:00 -0700
program_start_date:
  default: Sat, 22 Jun 2013
program_end_date:
  default: Mon, 24 Aug 2013
check_back_date:
  default: Sat, 1 Feb 2014
mail_from:
  default: reu@ucsd.edu
password_min_length:
  format: int
  default: 6
attachment_max_size:
  format: int
  default: 10240
general_description:
  default: "h3. General Description\n\nThe National Science Foundation's Research Experience for Undergraduates (NSF-REU) program provides undergraduate students access to state-of-the-art facilities, the opportunity to work with accomplished and experienced faculty mentors, and to participate in highly collaborative, cutting-edge research projects.\n"
highlights:
  default: "h4. Highlights\n\n* $X,XXX stipend\n* On-campus housing or housing allowance\n* Travel to and from the REU Site\n* Hands-on research experience\n* Weekly professional development workshops\n* Social events"
eligibility_requirements:
  default: "h4. Eligibility Requirements\n\n* Full-time undergraduate student\n* U.S. citizen or permanent resident"
application_information:
  default: "h4. Application Information\n\n* Major components of the online application include: a personal statement, a copy of your unofficial school transcript (as a pdf), and contact information for one reference\n* The person writing your letter of recommendation will be contacted via e-mail and will submit their letter online\n* Once you begin an application, you can check the status of it any time by logging into this website\n* Only complete applications will be reviewed"
  