app_title:
  default: UCSD Bioengineerin NSFREU
domain:
  default: be.ucsd.edu/nsfreu
university:
  default: UC San Diego
department:
  default: Bioengineering
application_deadline:
  default: Tue, 6 Mar 2012 00:00:00 -0700
program_start_date:
  default: Mon, 11 Jun 2012
program_end_date:
  default: Mon, 20 Aug 2012
check_back_date:
  default: Fri, 1 Feb 2013
mail_from:
  default: nsfreu@be.ucsd.edu
password_min_length:
  format: int
  default: 6
attachment_max_size:
  format: int
  default: 10240