app_title:
  default: University System of Taiwan (UST) Research Experience for UC San Diego Undergraduates
domain:
  default: reumanager.com/ust
university:
  default: University System of Taiwan
department:
  default: 
application_start:
  default: Mon, 7 Jan 2012 00:00:00 -0700
application_deadline:
  default: Tue, 16 Mar 2013 00:00:00 -0700
notification_date:
  default: Mon, 19 Apr 2013 00:00:00 -0700
program_start_date:
  default: Tue, 20 Jun 2013
program_end_date:
  default: Mon, 29 Aug 2013
check_back_date:
  default: Fri, 2 Jan 2014
mail_from:
  default: ucsd-ust@reumanager.com
password_min_length:
  format: int
  default: 7
attachment_max_size:
  format: int
  default: 10240
general_description:
  default: "h3. General Description\n\nUC San Diego is pleased to offer an apportunity for up to ten high-achieving, undergraduate students to conduct research at select labs within the University System of Taiwan during this summer."
highlights:
  default: "h4. Highlights\n\n* Open to students in all fields; UST will match students to lab based on mutual interest\n* Hands-on research experience"
eligibility_requirements:
  default: "h4. Eligibility Requirements\n\n* Full-time UC San Diego undergraduate student (graduating no earlier than fall 2013)\n* Students must cover the cost of the housing and meals ($1,350) plus airfare and personal expenses"
application_information:
  default: "h4. Application Information\n\n* Major components of the online application include:\n* A statement of purpose\n* A copy of your unofficial UCSD transcript (as a pdf)\n* Contact information for one reference\n* The person writing your letter of recommendation will be contacted via e-mail and will submit their letter online\n* Once you begin an application, you can check the status of it any time"
